apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: appsec
  name: appsec-github-stats-job
  namespace: appsec
spec:
  image: "{{ image }}"
  schedule: "0 6-18 * * *"
  timeZone: Europe/Oslo
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 1
  envFrom:
    - secret: appsec-stats-config
  env:
    - name: PUSH_GATEWAY_ADDRESS
      value: "prometheus-pushgateway.nais-system:9091"
    - name: GITHUB_API_VERSION
      value: "2026-03-10"
    - name: GITHUB_API_URL
      value: "https://api.github.com/"
    - name: GITHUB_TEAMS
      value: "appsec"
    - name: GITHUB_ORG
      value: "navikt"
  accessPolicy:
    outbound:
      rules:
        - application: prometheus-pushgateway
          namespace: nais-system
      external:
        - host: "api.github.com"
